import Foundation
import SwiftUI

extension Color {
    static let blackJumbo = Color(UIColor(named: "blackJumbo")!)
    static let blackJumbo2 = Color(UIColor(named: "blackJumbo2")!)
    static let doveGray = Color(UIColor(named: "doveGray")!)
    static let grayDark = Color(UIColor(named: "grayDark")!)
    static let grayJumbo = Color(UIColor(named: "grayJumbo")!)
    static let grayLight = Color(UIColor(named: "grayLight")!)
    static let greenDarkPistachio = Color(UIColor(named: "greenDarkPistachio")!)
    static let greenJumbo = Color(UIColor(named: "greenJumbo")!)
    static let greenJumboLight = Color(UIColor(named: "greenJumboLight")!)
    static let greenPistachio = Color(UIColor(named: "greenPistachio")!)
    static let grey = Color(UIColor(named: "grey") ?? UIColor.grey)
    static let guardswmanRed = Color(UIColor(named: "guardswmanRed") ?? UIColor.guardswmanRed)
    static let mercury = Color(UIColor(named: "mercury")!)
    static let pinkCencosud = Color(UIColor(named: "pinkCencosud")!)
    static let redError = Color(UIColor(named: "redError")!)
    static let separatorDefault = Color(UIColor(named: "separatorDefault")!)
    static let silver = Color(UIColor(named: "silver")!)
    static let whiteJumbo = Color(UIColor(named: "whiteJumbo")!)
    static let yellowInfo = Color(UIColor(named: "yellowInfo")!)
    static let neutral200 = Color(UIColor(named: "neutral200")!)
    static let neutral400 = Color(UIColor(named: "neutral400")!)
    static let newGreenDarkPistachio = Color(UIColor(named: "newGreenDarkPistachio")!)
    static let backgroundShopperMessage = Color(UIColor(named: "backgroundShopperMessage")!)
    static let backgroundUserMessage = Color(UIColor(named: "backgroundUserMessage")!)
    static let backgroundStartEndMessage = Color(UIColor(named: "backgroundStartEndMessage")!)
    static let backgroundChatShopperDivider = Color(UIColor(named: "backgroundChatShopperDivider")!)
    static let backgroundChatShopperButtonDisabled = Color(UIColor(named: "backgroundChatShopperButtonDisabled")!)
    static let blueCencoPay = Color(UIColor(named: "blueCencoPay")!)
    static let greenBackgroundCartButton = Color(UIColor(named: "greenBackgroundCartButton")!)
    static let placeHolder = Color(UIColor(named: "placeHolder")!)
    static let yellowInfoPill = Color(UIColor(named: "yellowInfoPill")!)
    static let systemBackgroundColor = Color(UIColor.systemBackground)
}

